In [31]:
import re
from functools import reduce
import itertools
from collections import Counter
import numpy as np
from dataclasses import dataclass, field


@dataclass
class Node():
    x: int 
    y: int 
    dist: int = field(compare=False)
    
    def neighbors(self, ymax, xmax):
       x, y = self.x, self.y
       candidates = [
            [x, y-1],
            [x-1, y],
            [x+1, y],
            [x, y+1],
       ]
       return [Node(xi[0],xi[1],self.dist+1) for xi in  list(filter(lambda k: 0 <= k[0] < xmax and 0 <= k[1] < ymax, candidates))]
 
    

sample = """...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
..........."""


def get_input(n):
    with open('input_'+n+'.txt', 'r') as infile:
        return infile.read().strip()


puzzle = get_input('21')

def parse_input(puzzle):
    lines = puzzle.strip().split('\n')
    lines = list(map(lambda x: list(x.__iter__()), lines))
    res = np.array(lines)
    print(f'read data of shape {res.shape}')
    return res


def solve1(puzzle, thresh):
    layout = parse_input(puzzle)
    start = np.where(layout == 'S')
    xy = (start[1][0],start[0][0])
    start = Node(*xy, 0)

    visited = [start]
    open_nodes = [start]
    

    while len(open_nodes) > 0:
        n = open_nodes.pop(0)
        neighbors = n.neighbors(*layout.shape)
        for n in neighbors:
            if n in visited or layout[n.y, n.x] == '#':
                continue
            if n.dist > thresh:
                continue
            open_nodes.append(n)
            visited.append(n)
        #print(len(visited), len(open_nodes))
    hits = np.zeros(layout.shape)
    for v in visited:
        hits[v.y,v.x] = v.dist

    print(hits)
    
    return len([n for n in visited if n.dist <= thresh and (n.x+n.y) %2 == thresh%2 ])

assert solve1(sample,6) == 16


read data of shape (11, 11)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 6. 0. 0.]
 [0. 6. 0. 4. 0. 2. 3. 4. 0. 0. 0.]
 [6. 5. 4. 3. 0. 1. 0. 5. 6. 0. 0.]
 [0. 0. 0. 2. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 2. 0. 6. 0. 0. 0. 0.]
 [0. 6. 5. 4. 3. 4. 5. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
solve1(puzzle, 64)

read data of shape (131, 131)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


3733